# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/pyCRLD',
                'doc_host': 'https://wbarfuss.github.io',
                'git_url': 'https://github.com/wbarfuss/pyCRLD',
                'lib_path': 'pyCRLD'},
  'syms': {}}
