name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        pip install .[dev]

    - name: Checkout submodules
      run: |
        git submodule init
        git submodule update



    - name: List installed packages
      run: |
        pip list

    - name: Inspect installed package
      run: |
        ls $(python -c "import site; print(site.getsitepackages()[0])")/pyCRLD

    # Use --nbval-lax to run notebooks without checking output
    - name: Run notebook tests
      run: |
        pytest --nbval-lax --pyargs nbs --ignore=nbs/.ipynb_checkpoints
